#!/bin/bash
if [ -f resources/image_v1.squashfs ]; then
	rm -f resources/image_v1.squashfs 
fi;
mksquashfs resources/root resources/image_v1.squashfs
if [ $? == 0 ]; then
    mv resources/image_v1.squashfs initramfs/mnt/cdrom/gentoo/
fi;
if [ $? == 0 ]; then
   if [ -f srv/pxeboot/gentoo/initramfs_squash.gz  ]; then
	   rm -f srv/pxeboot/gentoo/initramfs_squash.gz
   fi;
	   cd initramfs && find . -print | cpio -o -H newc | gzip -9 > ../srv/pxeboot/gentoo/initramfs_squash.gz
   cd ..
fi;
chown nobody:nogroup srv/pxeboot/gentoo/initramfs_squash.gz
chmod 666 srv/pxeboot/gentoo/initramfs_squash.gz
./export

